version: '2'
services:
  wpdb:
    image: mariadb:latest
    ports:
      - "12021:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  wp:
    image: wordpress:latest
    volumes: 
      - ./html:/var/www/html
    ports:
      - "12020:80"
    links:
      - wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 12121:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: wpdb
    links:
    - wpdb:mysql